info:
  name: Eureka server
  contact: Jinku

server:
  port: 8761
eureka:
  instance:
    hostname: 127.0.0.1
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    # 是否注册到eurekaserver
    registerWithEureka: false
    # 是否拉取信息
    fetchRegistry: false
    # eureka server地址
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    # false 关闭自我保护，剔除心跳检测异常的服务
    enableSelfPreservation: false